apiVersion: v1
kind: Service
metadata:
  name: netology-external-net
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      nodePort: 30080
    - name: multitool
      port: 8080
      protocol: TCP
      nodePort: 30880
  selector:
    app: nginx
  type: NodePort
