apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-box
  labels:
    app: bs_box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bs_box
  template:
    metadata:
      labels:
        app: bs_box
    spec:
      containers:
        - name: app1
          image: busybox
          command: ['sh', '-c', 'while true; do echo `date +"%H:%M:%S"` >> /output/log.txt; sleep 5; done']
          volumeMounts:
            - name: vol
              mountPath: /output
        - name: multitool
          image: wbitt/network-multitool:latest
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
          volumeMounts:
            - name: vol
              mountPath: /input
      volumes:
        - name: vol
          hostPath:
            path: /var/data
