---
# tasks file for nginx
# - name: "Ensure that nginx is installed."
#   apt: 
#     name:
#       - nginx
#     state: present

- name: "Update apt Cache"
  apt: 
    update_cache: yes
    force_apt_get: yes
- name: "Wait for APT Lock"
  shell:  "while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;"
- name: "Ensure that nginx is installed."
  apt: 
    name:
      - nginx
    state: present

- set_fact:
    my_devices: "{{ ansible_devices.keys()|
                  reject('match', '^loop(.*)$')|
                  list }}"

# Create custom index.html from template
# - name: "Add Index page."
#   template:
#     src: "index.html.j2"
#     dest: "/var/www/html/index.html"
#     owner: root
#     group: root
#     mode: 0755
#   notify: "Restart nginx"

- name: "Wait for port {{ nginx_port }} to become open on the host, don't start checking for 10 seconds"
  wait_for:
    port: "{{ nginx_port }}"
    delay: 5