---
- name: Prepare to install kuber cluster
  ansible.builtin.import_playbook: prepare.yml

- name: Install kuber cluster
  ansible.builtin.import_playbook: kubespray/cluster.yml

- name: Work with configs
  ansible.builtin.import_playbook: config.yml

- name: Install monitoring tools
  ansible.builtin.import_playbook: install-monitoring.yml

- name: Deploy app
  ansible.builtin.import_playbook: deploy-app.yml