---
vector_version: "0.39.0"
vector_arch: "amd64"

vector_template: vector.yaml.j2
vector_config_file: /etc/vector/vector.yaml

sources:
  demo_logs:
    type: demo_logs
    format: apache_common
    lines:
      - line1
sinks:
  to_clickhouse:
    type: clickhouse
    inputs:
      - demo_logs
    database: logs
    endpoint: http://51.250.18.186:8123
    table: vector_table
    compression: gzip
    healthcheck: true
    skip_unknown_fields: true
transforms: