---
- name: test
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: ubuntu
  become: yes

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 600

  tasks:
    - name: Install Nginx Web Server on Debian Family
      apt:
        name:
          - nginx
          - jq
        state: latest
        update_cache: yes

    # cat /tmp/own.pass  | jq
    - name: save own secret
      copy:
        dest: /tmp/own.pass
        content: "{{ secrets[inventory_hostname]  }}"
      when: secrets[inventory_hostname] is defined

    # cat /tmp/all.pass  | jq
    - name: save all secrets
      copy:
        dest: /tmp/all.pass
        content: "{{ secrets }}"
      when: secrets is defined