---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse distrib
      block:
        - name: Get clickhouse distrib for all arch
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}_all.deb"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib for amd64 arch
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            mode: "0644"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ item }}"
      with_items:
        - ./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
        - ./clickhouse-client_{{ clickhouse_version }}_all.deb
        - ./clickhouse-server_{{ clickhouse_version }}_all.deb
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
  vars_files:
    - group_vars/clickhouse/vars.yml

- name: Install Vector
  hosts: vector
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.service:
        name: vector
        daemon_reload: true
        state: restarted
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_{{ vector_arch }}.deb"
        dest: "./vector_{{ vector_version }}_{{ vector_arch }}.deb"
        mode: "0644"
    - name: Install vector
      become: true
      ansible.builtin.apt:
        deb: "./vector_{{ vector_version }}_{{ vector_arch }}.deb"
    - name: Copy config
      tags:
        - config
      become: true
      ansible.builtin.template:
        src: "{{ vector_template }}"
        dest: "{{ vector_config_file }}"
        mode: "0644"
      notify: Restart vector service
    - name: Use the right config_file
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/vector
        line: "VECTOR_CONFIG={{ vector_config_file }}"
        state: present

    - name: Add vector user to systemd-journal group
      ansible.builtin.user:
        name: vector
        groups: systemd-journal
        append: true
      when: add_vector_journal_group | default('no')
      notify: Start vector service
    - name: Start Vector
      become: true
      ansible.builtin.service:
        state: started
        enabled: true
        name: vector

  vars_files:
    - group_vars/vector/vars.yml
