apiVersion: v1
kind: Pod
metadata:
  name: standalone-multitool
  labels:
    test: st_multitool
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - containerPort: 8080
