apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-front
  labels:
    app: nt_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nt_app
  template:
    metadata:
      labels:
        app: nt_app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-file
              mountPath: /usr/share/nginx/html/
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HTTP_PORT
      volumes:
      - name: html-file
        configMap:
          name: my-configmap