#cloud-config
bootcmd:
  - sysctl -w net.ipv4.ip_forward=1
  - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
ssh_pwauth: no
users:
 - name: ubuntu
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAJw5qmPMY6PAeaB39fk8NnZ2gTGkJzA0qlV2J9flbEM egushchin@thumbtack.net
